name: CI

on:
  push:
    branches:
      - main

  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format
    if: github.ref_name == 'main'
    uses: ./.github/workflows/format.yml
    secrets: inherit
    with:
      ref: ${{ github.head_ref || github.ref }}

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18]
      
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Test
        run: pnpm test:ci
   
  dispatch_release:
    name: Dispatch Release
    needs: [test]
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      ref: ${{ github.ref }}
    