name: NPM

on: workflow_dispatch

defaults:
  run:
    shell: bash

env: 
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_CONFIG_PROVENANCE: true

permissions:
  contents: read
  id-token: write
 
jobs:
  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_TOKEN }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Setup User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get Latest Tag
        id: get_latest_tag
        run: echo "tag=$(git describe --tags --match="astro-portabletext*" --abbrev=0)" >> $GITHUB_OUTPUT
      
      - name: Reset to Latest Tag
        run: git reset --hard ${{ steps.get_latest_tag.outputs.tag }}
      
      - name: Install Dependencies
        run: pnpm install --filter astro-portabletext

      - name: Publish
        run: pnpm publish --filter astro-portabletext --no-git-checks
