name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release / Pull Request
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created && startsWith(steps.release.outputs.tag_name, 'astro-portabletext') }}
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Dispatch NPM
        if: ${{ steps.release.outputs.releases_created && startsWith(steps.release.outputs.tag_name, 'astro-portabletext') }}
        run: gh workflow run NPM
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN }}
