name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest

      - name: Dispatch NPM
        if: ${{ steps.release.outputs.releases_created && startsWith('astro-portabletext', steps.release.outputs.tag_name) }}
        run: gh workflow run NPM
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN }}
