name: Release Please PR

on:
  workflow_dispatch:
  push:
    branches:
      - 'release-please--**'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 26
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(release): sync pnpm lockfile"