name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release / Pull Request
        uses: googleapis/release-please-action@v4
        id: release

      - name: Publish to NPM?
        id: npm
        run: | 
          echo "dispatch=${{ steps.release.outputs['astro-portabletext--release_created'] || 'false' }}" >> $GITHUB_OUTPUT
  
      - uses: actions/checkout@v4
        if: ${{ steps.npm.outputs.dispatch == 'true' }}
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Dispatch NPM Workflow
        if: ${{ steps.npm.outputs.dispatch == 'true' }}
        run: gh workflow run NPM
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN }}
